server:
  port: 9095


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: pass

  datasource:
    url: jdbc:postgresql://localhost:5432/telegram
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true