server:
  port: 9095


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: pass

  datasource:
    url: jdbc:postgresql://localhost:5432/telegram
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true


token: 6019516263:AAHGIjKyXDZIiGS_UFYUctTKA81443yPXXo
service:
  file_info:
    uri: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
  file_storage:
    uri: https://api.telegram.org/file/bot{token}/{filePath}

link:
  address: 127.0.0.1:8091

hashValue: maSzVTVH6e0NtPt1dMuy62cfQGU3sMzS


